spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${SUPABASE_DB_HOST:aws-1-eu-west-1.pooler.supabase.com}:${SUPABASE_DB_PORT:5432}/${SUPABASE_DB_NAME:postgres}?sslmode=${SUPABASE_SSL_MODE:require}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${SUPABASE_DB_USER:postgres.ahyhdieaxbhwlreepogy}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${SUPABASE_DB_PASSWORD:Vendorlink@123}}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
